name: Publish container image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**.md", "**.yml" ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Support multi-arch builds
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: cayman
        tags: latest
        platforms: linux/amd64,linux/arm64/v8
        containerfiles: |
          ./Containerfile.Linux

    - name: Registry owner to lowercase
      env:
        GHOWNER: '${{ github.repository_owner }}'
        DHOWNER: '${{ secrets.DOCKERHUB_USERNAME }}'
      run: |
        echo "GHOWNER_LC=${GHOWNER,,}" >> ${GITHUB_ENV}
        echo "DHOWNER_LC=${DHOWNER,,}" >> ${GITHUB_ENV}

    - name: Push to GitHub Container Registry
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ env.GHOWNER_LC }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push to Docker Hub
      id: push-to-docker
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/${{ env.DHOWNER_LC }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Print image url
      run: |
        echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
        echo "Image pushed to ${{ steps.push-to-docker.outputs.registry-paths }}"
